# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxCmO7crIttljCYRaJ9jv4wzwrK8qPXB
"""

import matplotlib.pyplot as plt
import pandas as pd

brand_counts = movies['brand'].value_counts()

sns.set_style("whitegrid")

plt.figure(figsize=(10, 5))
sns.barplot(x=brand_counts.index, y=brand_counts.values, palette='viridis')

plt.title('Distribuição das marcas', fontsize=18)
plt.xlabel('Marca', fontsize=15)
plt.ylabel('Numero de anuncios', fontsize=15)
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()



import matplotlib.pyplot as plt
import pandas as pd

gear_counts = movies['gear'].value_counts()

plt.figure(figsize=(10, 5))
plt.bar(gear_counts.index, gear_counts.values, color='red')

plt.title('Distribuição dos tipos de marcha', fontsize=18)
plt.xlabel('Tipo de Marcha', fontsize=15)
plt.ylabel('Numero de anuncios', fontsize=15)
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd

fuel_counts = movies['fuel'].value_counts()

plt.figure(figsize=(10, 5))
plt.bar(fuel_counts.index, fuel_counts.values, color='blue')

plt.title('Distribuição dos tipos de combustível', fontsize=18)
plt.xlabel('Tipo de Combustível', fontsize=15)
plt.ylabel('Numero de anuncios', fontsize=15)
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()